// EDIT TEKS DAN FOTO DI SINI. Tidak perlu mengubah script.js.
window.MEMORY_CONFIG = {
  siteName: 'selalu kamu',
  pageTitle: 'Semua tentang kamu',
  eyebrow: 'seseorang yang selalu bikin senyum',
  headline: 'Hal-hal indah',
  highlight: 'tentang kamu.',
  footer: 'sederhana, tapi istimewa. seperti kamu.',

  // Taruh foto di assets/foto/, dengan nomor 01 sampai 15.
  // Format boleh campur: JPG, JPEG, PNG, WEBP, GIF, AVIF, HEIC, atau HEIF.
  // Contoh: 01.jpg, 02.PNG, 03.heic. Cukup satu file untuk setiap nomor.
  // src TANPA ekstensi: format dan huruf besar/kecil umum dicari otomatis.
  // HEIC/HEIF: buka index.html lewat Live Server, bukan klik dua kali file.
  // Pertahankan ekstensi asli. Mengganti .heic jadi .jpg bukan konversi.
  photos: [
    { src: 'assets/foto/01', caption: 'senyum favoritku', position: '50% 50%' },
    { src: 'assets/foto/02', caption: 'dia dan caranya bersinar', position: '50% 50%' },
    { src: 'assets/foto/03', caption: 'selalu bikin senyum', position: '50% 50%' },
    { src: 'assets/foto/04', caption: 'sederhana, tapi istimewa', position: '50% 50%' },
    { src: 'assets/foto/05', caption: 'hal kecil yang kusuka', position: '50% 50%' },
    { src: 'assets/foto/06', caption: 'secerah itu senyumnya', position: '50% 50%' },
    { src: 'assets/foto/07', caption: 'caranya jadi diri sendiri', position: '50% 50%' },
    { src: 'assets/foto/08', caption: 'tentang seseorang yang spesial', position: '50% 50%' },
    { src: 'assets/foto/09', caption: 'rasanya ingin terus melihatnya', position: '50% 50%' },
    { src: 'assets/foto/10', caption: 'satu dari banyak alasanku', position: '50% 50%' },
    { src: 'assets/foto/11', caption: 'dia, lagi dan lagi', position: '50% 50%' },
    { src: 'assets/foto/12', caption: 'selalu ada yang bikin kagum', position: '50% 50%' },
    { src: 'assets/foto/13', caption: 'sepotong cerah dalam hariku', position: '50% 50%' },
    { src: 'assets/foto/14', caption: 'ekspresi gemesnya', position: '50% 50%' },
    { src: 'assets/foto/15', caption: 'semuanya, tentang kamu', position: '50% 50%' }
  ],
  phrases: [
    'senyumnya bikin hari cerah', 'ada saja yang bikin kagum',
    'dia, dengan segala hal kecilnya', 'seseorang yang istimewa',
    'sesederhana melihat dia bahagia', 'caranya tertawa',
    'cantiknya jadi diri sendiri', 'tentang dia, lagi dan lagi',
    'hal favoritku: senyumnya','lucunya', 'semoga harinya selalu cerah',
    'selalu berhasil bikin senyum', 'kamu punya tempat di cerita ini',
    'cerita ini penuh tentang kamu', 'seindah itu di mataku',
    'kamu dan seribu hal menarik', 'ingin melihatnya terus bahagia',
    'satu senyum, banyak cerita', 'tatapannya punya cerita',
    'hal-hal kecil darinya', 'kamu layak mendapat hal baik',
    'semoga hatinya selalu hangat', 'cerahnya menular',
    'ada tenang saat melihatnya', 'kamu, tanpa perlu jadi siapa-siapa',
    'sederhana dan berkesan', 'satu foto, satu alasan tersenyum',
    'kamu adalah hal-hal favoritku', 'caranya menikmati hari',
    'semoga mimpinya satu-satu mekar', 'senyumnya layak dirayakan',
    'yang membuat hari terasa ringan', 'selalu ada cerita tentang kamu',
    'cantik, bahkan dalam hal sederhana', 'ingin menyimpan momen ini',
    'kamu membuat cerita ini berwarna', 'seperti bunga, tumbuh dengan caranya',
    'sanisha','sayangku','cintaku','duniaku','cantikku','manis senyumnya',
    'kamu, alasan senyum hari ini', 'ada cerah di setiap tawamu',
    'senyum kecil yang selalu kuingat', 'betapa manisnya kamu hari ini',
    'kamu bikin dunia terasa hangat', 'rasanya senang mengenalmu',
    'setiap ekspresimu punya cerita', 'kamu dan pesonamu sendiri',
    'aku suka caramu melihat dunia', 'bahagiamu ikut bikin bahagia',
    'ada bunga di setiap ceritamu', 'kamu seperti pagi yang cerah',
    'tawamu, nada paling kusuka', 'senyummu bikin lupa mendung',
    'begitu banyak hal baik darimu', 'kamu selalu punya warna sendiri',
    'manisnya tak perlu dibuat-buat', 'caramu tersenyum itu istimewa',
    'kamu membawa hangat ke sini', 'sebuah cerita bernama kamu',
    'ada kamu, ada alasan tersenyum', 'semoga bahagiamu panjang',
    'hari baik semoga menemukanmu', 'semoga langkahmu terasa ringan',
    'semoga senyummu selalu pulang', 'semoga lelahmu bertemu tenang',
    'semoga harimu banyak kabar baik', 'semoga impianmu pelan-pelan nyata',
    'semoga dunia ramah padamu', 'semoga kamu bangga pada dirimu',
    'kamu pantas disayang dengan baik', 'kamu pantas punya hari indah',
    'terus tumbuh dengan caramu', 'mekar pelan-pelan juga indah',
    'tetap jadi kamu yang hangat', 'terima kasih sudah jadi dirimu',
    'aku suka sisi sederhanamu', 'aku suka semangat kecilmu',
    'aku suka caramu bercerita', 'aku suka melihatmu antusias',
    'aku suka caramu menikmati hal kecil', 'aku suka tawamu yang lepas',
    'aku suka saat kamu bahagia', 'aku suka semua ekspresi lucumu',
    'aku suka caramu menyapa hari', 'aku suka tenang yang kamu bawa',
    'kamu bikin hal biasa jadi manis', 'potret kecil, kesan yang lama',
    'satu tatapan, satu cerita baru', 'sebanyak ini yang kusuka darimu',
    'kenangan manis punya wajahmu', 'momen sederhana terasa berharga',
    'aku simpan senyummu di sini', 'halaman ini penuh warna kamu',
    'langit cerah untuk senyummu', 'bunga-bunga ikut merayakanmu',
    'kupu-kupu lewat membawa cerah', 'sehangat sinar pagi di jendela',
    'semanis bunga yang baru mekar', 'selembut angin di hari cerah',
    'kamu punya cahaya yang lembut', 'kamu indah dengan caramu',
    'cantikmu punya banyak cerita', 'ada manis di caramu tertawa',
    'ada teduh di senyum kecilmu', 'senyummu selalu punya tempat',
    'susah memilih foto favoritmu', 'semua sisi punya ceritanya',
    'di foto ini, kamu tetap istimewa', 'satu lagi potret yang kusuka',
    'melihatmu senyum, ikut senyum', 'gemasnya ada di hal-hal kecil',
    'ekspresi ini bikin senyum lagi', 'caramu tertawa selalu berkesan',
    'sesekali malu, tetap menggemaskan', 'senyum spontan paling kusuka',
    'ceritakan lagi hal yang kamu suka', 'aku senang mendengar ceritamu',
    'semangatmu juga ikut menular', 'hal kecil darimu terasa besar',
    'kamu memberi warna pada hari', 'ada banyak indah di dalam dirimu',
    'kebaikanmu selalu punya jejak', 'hatimu layak dijaga hangat',
    'perjalananmu layak dirayakan', 'langkah kecilmu tetap berarti',
    'bangga pada setiap usahamu', 'kamu sudah sejauh ini',
    'istirahat juga bagian dari tumbuh', 'semoga ada tenang di sela harimu',
    'semoga kamu sering tertawa lepas', 'semoga banyak bunga di ceritamu',
    'semoga esok membawakan senyum', 'semoga hatimu selalu punya ruang',
    'semoga hari ini memelukmu hangat', 'semoga mimpimu menemukan jalan',
    'kamu dan hal-hal yang kamu cintai', 'wajah bahagia yang ingin kuingat',
    'senyum ini layak disimpan', 'kenangan ini hangat karena kamu',
    'tentangmu, selalu ada cerita', 'setiap foto menyimpan cerahmu',
    'kamu hadir dalam hal-hal manis', 'terima kasih untuk senyum hari ini',
    'aku berharap kamu selalu bahagia', 'tetap bersinar dengan caramu',
    'kamu seperti kabar baik', 'ada senyum setelah melihatmu',
    'cerahnya hari ini mirip tawamu', 'hal kecil, rasa senang yang besar',
    'satu halaman untuk mengagumimu', 'semuanya terasa lebih berwarna'
  ],

  // Opsional: taruh musik di assets/musik/lagu.mp3,
  // lalu ubah '' menjadi 'assets/musik/lagu.mp3'.
  // Musik dicoba otomatis setelah pembuka. Jika diblokir browser, sentuh halaman.
  // Tambahkan musicAutoplay: false jika ingin musik hanya lewat tombol.
  music: 'assets/musik/music.mpeg',
  musicVolume: 0.45,
  natureAnimation: true,
  // Semakin besar angkanya, semakin pelan foto bergerak.
  animationDuration: 33,
  introDuration: 35
};
